Vagrant.configure("2") do |config|
  config.vm.hostname  = "db01"
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.12"
  config.vm.network "forwarded_port", guest: 3306, host: 3306
end