Vagrant.configure("2") do |config|
  config.vm.hostname  = "app-01"
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
end